"""
report_service.py - PDF field report generation using fpdf2.
"""
import os
import time
from pathlib import Path
from typing import Any

from fpdf import FPDF
from loguru import logger

_REPORTS_DIR = Path("outputs/reports")


def _ensure_reports_dir() -> Path:
    _REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    return _REPORTS_DIR


def _health_color(score: int) -> tuple[int, int, int]:
    """Return (R, G, B) for a health score: green ≥70, yellow 40-69, red <40."""
    if score >= 70:
        return (34, 197, 94)
    if score >= 40:
        return (234, 179, 8)
    return (239, 68, 68)


class _ReportPDF(FPDF):
    """Custom FPDF subclass with header/footer."""

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(
            0,
            10,
            "Generated by AgriDrone AI System | YOLOv11 + Claude AI | NDSU Precision Agriculture",
            align="C",
        )


def generate_field_report(data: dict[str, Any]) -> str:
    """
    Generate a PDF field report and save it to outputs/reports/.

    Args:
        data: Dict containing (all optional except noted):
            - field_id (str, required)
            - crop_type (str, required)
            - scan_date (str, optional — defaults to current date)
            - gps_coordinates (str|None)
            - images_analyzed (int)
            - total_detections (int)
            - overall_field_health (int, 0-100)
            - risk_level (str)
            - primary_issues (list[dict])
            - recommendations (list[dict])
            - research_notes (str)
            - follow_up_scan_days (int)

    Returns:
        Absolute path to the generated PDF file.
    """
    out_dir = _ensure_reports_dir()

    field_id = data.get("field_id", "unknown")
    crop_type = data.get("crop_type", "unknown")
    scan_date = data.get("scan_date") or time.strftime("%Y-%m-%d")
    health_score = int(data.get("overall_field_health", 0))

    pdf = _ReportPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── 1. Header ──────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(30, 64, 175)
    pdf.cell(0, 12, "Precision Agriculture UAV Field Report", ln=True, align="C")
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 7, f"Field ID: {field_id}   |   Crop: {crop_type}   |   Date: {scan_date}", ln=True, align="C")
    pdf.ln(4)

    # Divider
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # ── 2. Flight Summary ──────────────────────────────────────
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 8, "Flight Summary", ln=True)
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)

    gps = data.get("gps_coordinates")
    if gps:
        pdf.cell(0, 6, f"GPS Coordinates: {gps}", ln=True)

    images = data.get("images_analyzed", 0)
    total_det = data.get("total_detections", 0)
    pdf.cell(0, 6, f"Images Analyzed: {images}", ln=True)
    pdf.cell(0, 6, f"Total Detections: {total_det}", ln=True)
    risk = data.get("risk_level", "unknown")
    pdf.cell(0, 6, f"Risk Level: {risk.upper()}", ln=True)
    follow_up = data.get("follow_up_scan_days", 7)
    pdf.cell(0, 6, f"Recommended Follow-Up Scan: {follow_up} days", ln=True)
    pdf.ln(6)

    # ── 3. Field Health Score ──────────────────────────────────
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 8, "Field Health Score", ln=True)
    pdf.ln(2)

    r, g, b = _health_color(health_score)

    # Score background box
    box_x = 70
    box_y = pdf.get_y()
    pdf.set_fill_color(r, g, b)
    pdf.rect(box_x, box_y, 70, 22, style="F")

    # Score text
    pdf.set_xy(box_x, box_y + 2)
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(70, 18, f"{health_score} / 100", align="C")

    pdf.set_y(box_y + 26)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(100, 100, 100)
    label = "Good" if health_score >= 70 else ("Fair" if health_score >= 40 else "Poor")
    pdf.cell(0, 5, f"Rating: {label}", ln=True, align="C")
    pdf.ln(6)

    # ── 4. Detection Breakdown Table ───────────────────────────
    issues = data.get("primary_issues", [])
    if issues:
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 8, "Detection Breakdown", ln=True)
        pdf.ln(2)

        # Table header
        col_w = [70, 35, 35, 50]
        headers = ["Issue", "Area Affected %", "Severity", "Category"]
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_fill_color(30, 64, 175)
        pdf.set_text_color(255, 255, 255)
        for i, h in enumerate(headers):
            pdf.cell(col_w[i], 8, h, border=1, fill=True, align="C")
        pdf.ln()

        # Table rows
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(40, 40, 40)
        for idx, issue in enumerate(issues):
            if idx % 2 == 0:
                pdf.set_fill_color(240, 240, 250)
            else:
                pdf.set_fill_color(255, 255, 255)

            pdf.cell(col_w[0], 7, str(issue.get("issue", ""))[:40], border=1, fill=True)
            pdf.cell(col_w[1], 7, f"{issue.get('affected_area_pct', 0):.1f}%", border=1, fill=True, align="C")
            sev = issue.get("severity", 0)
            pdf.cell(col_w[2], 7, f"{sev:.2f}" if isinstance(sev, (int, float)) else str(sev), border=1, fill=True, align="C")
            pdf.cell(col_w[3], 7, str(issue.get("zone", "")), border=1, fill=True, align="C")
            pdf.ln()

        pdf.ln(6)

    # ── 5. AI Recommendations ──────────────────────────────────
    recs = data.get("recommendations", [])
    if recs:
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 8, "AI Recommendations", ln=True)
        pdf.ln(2)

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        for i, rec in enumerate(recs, 1):
            action = rec.get("action", "")
            priority = rec.get("priority", "medium")
            product = rec.get("input", "")
            rate = rec.get("rate", "")
            zone = rec.get("zone", "")

            line = f"{i}. [{priority.upper()}] {action}"
            if product:
                line += f"  —  Product: {product}"
            if rate:
                line += f"  —  Rate: {rate}"
            if zone:
                line += f"  —  Zone: {zone}"

            pdf.multi_cell(0, 6, line)
            pdf.ln(1)

        pdf.ln(4)

    # ── 6. Research Notes ──────────────────────────────────────
    notes = data.get("research_notes", "")
    if notes:
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 8, "Research Notes", ln=True)
        pdf.ln(2)

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        # fpdf2 multi_cell handles wrapping
        pdf.multi_cell(0, 5, notes)
        pdf.ln(4)

    # ── Save ───────────────────────────────────────────────────
    ts = time.strftime("%Y%m%d_%H%M%S")
    safe_field = "".join(c if c.isalnum() or c in "-_" else "_" for c in field_id)
    filename = f"field_report_{safe_field}_{ts}.pdf"
    filepath = out_dir / filename

    pdf.output(str(filepath))
    logger.info(f"Field report saved: {filepath}")
    return str(filepath.resolve())
